### ISSUE TITLE
使用 blocklet-page 构建 did-connect 的站点

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/did-connect#17]
DID Connect 的站点至少包括如下内容：

- What is DID Connect
- How DID Connect Works
- Live Demo? DID Wallet is Required
- DID Connect Protocol
- DID Connect SDK
- DID Connect Related Blocklets

**Comment by mave99a** [comment]
可以正好结合我9月需要写的这篇 paper需要的内容： https://github.com/WebOfTrustInfo/rwot11-the-hague/blob/master/advance-readings/did-connect.md
