### ISSUE TITLE
[BUG]: 必然重现的钱包端错误，但可能是 DID connect导致

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/did-connect#74]
# 🐛 Bug Report

## 详细描述

1. did connect 链接一个站点
2. 不要提供passport
3. 选择切换passport
4. 还是不提供passport
5. 钱包 / web 同时出错

![IMG_0344](https://user-images.githubusercontent.com/41923/217142372-504ce2c8-ae4e-4c1e-87f0-194178e5b271.jpeg)

**Comment by wangshijun** [comment]
在 https://www.zoeis.me/en/demo 复现了，报错信息如下：

![Screenshot 2023-02-18 at 11 16 50](https://user-images.githubusercontent.com/719985/219828893-593ef778-d9a1-403b-94c4-0c657906155a.png)

**Comment by wangshijun** [comment]
fixed in [1.8.66-beta-ff281dd5](https://www.npmjs.com/package/@blocklet/cli/v/1.8.66-beta-ff281dd5)
